on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '#skip'))
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:8080
      - name: Deploy app
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && !contains(github.head_commit.message, '#skip')
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Send Discord notification
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: Deployment ${JOB_STATUS}
          description: |
            **Commit**: ${GITHUB_SHA}
            **Branch**: ${GITHUB_REF}
            **Repository**: ${GITHUB_REPOSITORY}
        env:
          JOB_STATUS: ${{ job.status }}
